small shellscript changes

diff --git a/bin/git_SG b/bin/git_SG
--- a/bin/git_SG
+++ b/bin/git_SG
@@ -4,10 +4,27 @@
 # so git log/show doesn't complaint about switch `S' not having a value
 # also supports git -C log/show/.. -S ...
 
-if [[ "$2" == "-G" ]] || [[ "$2" == "-S" ]]; then
+# Exit on error. Append "|| true" if you expect an error.
+set -o errexit
+
+# Exit on error inside any functions or subshells.
+set -o errtrace
+
+# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
+set -o nounset
+
+# Catch the error in case mysqldump fails (but gzip succeeds) in `mysqldump |gzip`
+set -o pipefail
+
+# Turn on tracesif run with TRACE=1 for debugging
+if [[ ${TRACE-0} == "1" ]]; then
+	set -o xtrace
+fi
+
+if [[ $2 == "-G" ]] || [[ $2 == "-S" ]]; then
 	args1=("${1}")
 	args2=("${@:3}")
-elif [[ "$1" == "-C" ]] && { [[ "$4" == "-G" ]] || [[ "$4" == "-S" ]]; }; then
+elif [[ $1 == "-C" ]] && { [[ $4 == "-G" ]] || [[ $4 == "-S" ]]; }; then
 	args1=("${@:1:3}")
 	args2=("${@:5}")
 else
diff --git a/bin/pickaxe-diff b/bin/pickaxe-diff
--- a/bin/pickaxe-diff
+++ b/bin/pickaxe-diff
@@ -5,14 +5,25 @@
 #                to only show hunks containing the searched string/regex.
 # https://gist.github.com/phil-blain/2a1cf81a0030001d33158e44a35ceda6
 
-set -Eeuo pipefail
+# Exit on error. Append "|| true" if you expect an error.
+set -o errexit
+
+# Exit on error inside any functions or subshells.
+set -o errtrace
+
+# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
+set -o nounset
+
+# Catch the error in case mysqldump fails (but gzip succeeds) in `mysqldump |gzip`
+set -o pipefail
+
+# Turn on tracesif run with TRACE=1 for debugging
+if [[ ${TRACE-0} == "1" ]]; then
+	set -o xtrace
+fi
 
 # shellcheck disable=SC2154
 trap 'rc=$?; echo "${0}: ERR trap at line ${LINENO} (return code: $rc)"; exit $rc' ERR
-
-if [ -n "${PICKAXEDIFF_TRACE+x}" ]; then
-	set -x
-fi
 
 echo_meta() {
 	echo "${color_meta}$1${color_none}"
